{% set name = "csdms-topoflow-snow-degree-day" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/topoflow-bridge

requirements:
  build:
    - bmi-babel
    - topoflow
  run:
    - bmi-babel
    - topoflow

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Snowmelt-Degree-Day
  license: Apache
  summary: |
    SnowDegreeDay is a snowmelt process component included
    within the spatially distributed hydrologic model TopoFlow. It uses
    the degree day technique for modeling snowmelt.

